version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@2.0.0





workflows:
  build:
    jobs:
      - node/test:
          filters:
            branches:
              only:
                - main

      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - main

      - heroku/deploy-via-git:
          app-name: hoke-app-iww2
          requires:
            - "node/test"
            - "node/run"
          filters:
            branches:
              only:
                - main

