version: 2.1

orbs:
  node123: circleci/node@5.0.3

jobs:
  build-test:
    docker:
      - image: cimp/base:stable

    steps:
      - checkout
      - node123/install:
          node-version: '16.13'
      - node123/install-packages:
          cache-path: ~/project/node_modules

      - run: npm test


workflows:
  build:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - main

